// lang.js

export const ULKE_SOZLUGU = {
    "Meksika": { en: "Mexico", de: "Mexiko" },
    "Güney Afrika": { en: "South Africa", de: "Südafrika" },
    "Güney Kore": { en: "South Korea", de: "Südkorea" },
    "Çek Cumhuriyeti": { en: "Czech Republic", de: "Tschechien" },
    "Kanada": { en: "Canada", de: "Kanada" },
    "Bosna-Hersek": { en: "Bosnia & Herz.", de: "Bosnien-Herz." },
    "Katar": { en: "Qatar", de: "Katar" },
    "İsviçre": { en: "Switzerland", de: "Schweiz" },
    "Brezilya": { en: "Brazil", de: "Brasilien" },
    "Fas": { en: "Morocco", de: "Marokko" },
    "Haiti": { en: "Haiti", de: "Haiti" },
    "İskoçya": { en: "Scotland", de: "Schottland" },
    "ABD": { en: "USA", de: "USA" },
    "Paraguay": { en: "Paraguay", de: "Paraguay" },
    "Avustralya": { en: "Australia", de: "Australien" },
    "Türkiye": { en: "Turkey", de: "Türkei" },
    "Almanya": { en: "Germany", de: "Deutschland" },
    "Kurasao": { en: "Curacao", de: "Curaçao" },
    "Fildişi Sahili": { en: "Ivory Coast", de: "Elfenbeinküste" },
    "Ekvador": { en: "Ecuador", de: "Ecuador" },
    "Hollanda": { en: "Netherlands", de: "Niederlande" },
    "Japonya": { en: "Japan", de: "Japan" },
    "İsveç": { en: "Sweden", de: "Schweden" },
    "Tunus": { en: "Tunisia", de: "Tunesien" },
    "Belçika": { en: "Belgium", de: "Belgien" },
    "Mısır": { en: "Egypt", de: "Ägypten" },
    "İran": { en: "Iran", de: "Iran" },
    "Yeni Zelanda": { en: "New Zealand", de: "Neuseeland" },
    "İspanya": { en: "Spain", de: "Spanien" },
    "Yeşil Burun Adaları": { en: "Cape Verde", de: "Kap Verde" },
    "Suudi Arabistan": { en: "Saudi Arabia", de: "Saudi-Arabien" },
    "Uruguay": { en: "Uruguay", de: "Uruguay" },
    "Fransa": { en: "France", de: "Frankreich" },
    "Senegal": { en: "Senegal", de: "Senegal" },
    "Irak": { en: "Iraq", de: "Irak" },
    "Norveç": { en: "Norway", de: "Norwegen" },
    "Arjantin": { en: "Argentina", de: "Argentinien" },
    "Cezayir": { en: "Algeria", de: "Algerien" },
    "Avusturya": { en: "Austria", de: "Österreich" },
    "Ürdün": { en: "Jordan", de: "Jordanien" },
    "Portekiz": { en: "Portugal", de: "Portugal" },
    "Kongo DC": { en: "DR Congo", de: "DR Kongo" },
    "Özbekistan": { en: "Uzbekistan", de: "Usbekistan" },
    "Kolombiya": { en: "Colombia", de: "Kolumbien" },
    "İngiltere": { en: "England", de: "England" },
    "Hırvatistan": { en: "Croatia", de: "Kroatien" },
    "Gana": { en: "Ghana", de: "Ghana" },
    "Panama": { en: "Panama", de: "Panama" }
};

export function ulkeCevir(isim) {
    if (!isim) return isim;
    let dil = 'tr';
    try {
        const ayarlar = JSON.parse(localStorage.getItem('WC26SIM_AYARLAR'));
        if (ayarlar && ayarlar.dil) dil = ayarlar.dil;
    } catch(e) {
        console.warn("Dil ayarı okunamadı, varsayılan TR kullanılıyor.");
    }
    
    if (dil === 'tr') return isim;
    if (ULKE_SOZLUGU[isim] && ULKE_SOZLUGU[isim][dil]) {
        return ULKE_SOZLUGU[isim][dil];
    }
    return isim;
}

export const DIL_SOZLUGU = {
    tr: {
        ziyaretciMetni: "Toplam Ziyaret:",
        anaSayfaDon: "🏠 Ana Sayfa",
        anaBaslik: "DÜNYA KUPASI 2026<br><span style='color:#fff;'>SİMÜLATÖRÜ</span>",
        altBaslik: "Kendi turnuvanı yönet, tarihi yeniden yaz.",
        slotKariyer: "Kariyer",
        yeniKariyerAç: "Yeni Kariyer Aç ➕",
        devamEt: "Devam Et 🎮",
        kariyeriSil: "Kariyeri Sil 🗑️",
        bosSlot: "Kayıtlı kariyer bulunamadı.",
        durumGrup: "Maç Günü",
        durumSon32: "Son 32 Turu",
        durumSon16: "Son 16 Turu",
        durumCeyrek: "Çeyrek Final",
        durumYari: "Yarı Final",
        durumSampiyon: "🏆 Şampiyon Belli Oldu!",
        ilerleme: "İlerleme",
        takimSecBaslik: "TAKIMINI SEÇ",
        takimSecAlt: "Dünya Kupası hedefine hangi ülkeyle ulaşmak istersin?",
        secilenUlke: "Seçilen Ülke:",
        grupMetni: "Grup",
        kariyerBaslat: "Kariyeri Başlat 🚀",
        iptalEt: "İptal Et",
        hucum: "Hücum",
        ortaSaha: "Orta Saha",
        savunma: "Savunma",
        aktifKariyer: "Aktif Kariyer: Slot",
        menajersiz: "Menajersiz",
        grupGoster: "Grup Aşamasını Göster 🔽",
        grupGizle: "Grup Aşamasını Gizle 🔼",
        enIyiUcunculer: "En İyi 3.'ler",
        turnuvaDurumu: "Turnuva Durumu",
        grupAsamasiBitti: "Grup Aşaması Tamamlandı!",
        elemeAgaci: "Dünya Kupası Eleme Ağacı",
        buyukFinal: "BÜYÜK FİNAL 🏆",
        dunyaSampiyonu: "DÜNYA ŞAMPİYONU",
        belirsiz: "Belirsiz",
        henuzYok: "Henüz Yok",
        gununMansetSkoru: "Günün Manşet Skoru:",
        tabloTakim: "Takım",
        tabloO: "O", tabloG: "G", tabloB: "B", tabloM: "M",
        tabloAG: "AG", tabloYG: "YG", tabloAV: "AV", tabloP: "P",
        formda: "Formda", stabil: "Stabil", formsuz: "Formsuz",
        enIyiUcuncuEtiket: "En İyi 3. Sıralaması",
        sira: "Sıra",
        turSon32: "Son 32",
        turSon16: "Son 16",
        turCeyrek: "Çeyrek F.",
        turYari: "Yarı F.",
        turUcunculuk: "3.lük Maçı",
        turFinal: "Final",
        macGunuTamamla: "Maç Gününü Tamamla",
        tumTuruOyna: "Tüm Tur Maçlarını Oyna",
        son32Gec: "Son 32 Turuna Geç 🏆",
        sonrakiTuraGec: "Bir Sonraki Tura Geç ➡️",
        raporGoster: "📊 Turnuva Raporu",
        macOynaButon: "▶️ Oyna",
        macRaporuBaslik: "Maç Raporu",
        toplaOynama: "Topla Oynama",
        beklenenGol: "Beklenen Gol (xG)",
        toplamSut: "Toplam Şut",
        faul: "Faul",
        sariKartlar: "Sarı Kartlar",
        kirmiziKartlar: "Kırmızı Kartlar",
        istatistikBaslik: "Turnuva İstatistikleri",
        keskinNisanci: "🎯 Keskin Nişancı",
        golOrani: "Gol Oranı",
        enKotuDefans: "🧱 En Kötü Savunma",
        ygMac: "YG / Maç",
        enBüyükSurpriz: "🔥 En Büyük Sürpriz",
        hayalKirikligi: "😱 Hayal Kırıklığı",
        enKasapTakim: "⚔️ En Kasap Takım",
        faulMac: "Faul/Maç",
        linkGizlilikMetni: "Gizlilik Politikası",
        linkIletisimMetni: "İletişim",
        iletisimFormuBaslik: "Bizimle İletişime Geçin",
        formAdiniz: "Adınız:",
        formEposta: "E-Posta Adresiniz:",
        formMesajiniz: "Mesajınız:",
        formGonder: "Gönder 🚀",
        formGonderiliyor: "Gönderiliyor...",
        formBasari: "Mesajınız başarıyla gönderildi!",
        hataEposta: "Lütfen geçerli bir e-posta adresi giriniz.",
        hataGenel: "Mesaj gönderilirken bir sorun oluştu.",
        hataInternet: "İnternet bağlantınızı kontrol edin.",
        kapat: "Kapat",
        silOnay: "Sil 🗑️",
        silVazgec: "Vazgeç",
        silBaslik: "Kariyeri Sil",
        silMetin: "Seçilen yuvadaki tüm simülasyon verileri kalıcı olarak silinecektir. Emin misiniz?",
        turUyarisi: "aşamasındasınız. Lütfen önce bu turu tamamlayıp 'Sonraki Tura Geç' butonunu kullanın!",
        gizlilikP1: "Bu Dünya Kupası 2026 Simülatörü, kullanıcı deneyimini artırmak ve turnuva kayıtlarınızı tutmak için tamamen <strong>yerel tarayıcı hafızası (LocalStorage)</strong> kullanmaktadır.",
        gizlilikP2: "Hiçbir kişisel veriniz, IP adresiniz veya simülasyon ilerlemeniz uzak sunuculara aktarılmaz, kaydedilmez veya üçüncü şahıslarla paylaşılmaz. Oyununuz sadece kendi cihazınızda güvendedir.",
        
        modHizliSimule: "Hızlı Simüle",
        modHizliSimuleAlt: "Sadece takımını seç ve maçları simüle et. Taktiksel detaylarla uğraşmak istemeyenler için ideal.",
        modOzelGruplar: "Özel Gruplar",
        modOzelGruplarAlt: "Tüm 12 gruba takımları kendin yerleştir veya yapay zekaya karıştır! Fikstür yapısı bozulmadan yeni senaryolar yarat.",
        modTaktiksel: "Taktik Modu",
        modTaktikselAlt: "İlk 11'i sen belirle, dizilişleri seç ve oyun anlayışını ayarla. Tam kontrol ve derin menajerlik deneyimi.",
        modSecimBaslik: "Oyun Modunu Seç",
        modSecimAlt: "Turnuvayı nasıl oynamak istersin?",
        cgBaslik: "Grupları Kendin Belirle",
        cgAltMetin: "Takımları sürükle-bırak ile taşı veya havuza tıklayarak sıradaki boş gruba hızlıca gönder.",
        cgBtnKaristir: "🎲 Yapay Zekaya Karıştır",
        cgBtnSifirla: "🔄 Sıfırla",
        cgBtnOnayla: "✅ Onayla ve Devam Et",
        cgHavuzBaslik: "Takım Havuzu",
        taktikYonetimiBtn: "Takım Yönetimi 🧠",
        taktikTahtasi: "Taktik Tahtası",
        oyunPlani: "Oyun Planı",
        ilk11Yedekler: "İlk 11 ve Yedekler"
    },
    
    en: {
        ziyaretciMetni: "Total Visits:",
        anaSayfaDon: "🏠 Home",
        anaBaslik: "WORLD CUP 2026<br><span style='color:#fff;'>SIMULATOR</span>",
        altBaslik: "Manage your tournament, rewrite history.",
        slotKariyer: "Career",
        yeniKariyerAç: "Start New Career ➕",
        devamEt: "Continue 🎮",
        kariyeriSil: "Delete Career 🗑️",
        bosSlot: "No saved career found.",
        durumGrup: "Matchday",
        durumSon32: "Round of 32",
        durumSon16: "Round of 16",
        durumCeyrek: "Quarter Finals",
        durumYari: "Semi Finals",
        durumSampiyon: "🏆 Champion Crowned!",
        ilerleme: "Progress",
        takimSecBaslik: "SELECT YOUR TEAM",
        takimSecAlt: "Which country will you lead to World Cup glory?",
        secilenUlke: "Selected Country:",
        grupMetni: "Group",
        kariyerBaslat: "Start Career 🚀",
        iptalEt: "Cancel",
        hucum: "Attack",
        ortaSaha: "Midfield",
        savunma: "Defense",
        aktifKariyer: "Active Career: Slot",
        menajersiz: "No Manager",
        grupGoster: "Show Group Stage 🔽",
        grupGizle: "Hide Group Stage 🔼",
        enIyiUcunculer: "Best 3rd Places",
        turnuvaDurumu: "Tournament Status",
        grupAsamasiBitti: "Group Stage Completed!",
        elemeAgaci: "World Cup Knockout Bracket",
        buyukFinal: "GRAND FINAL 🏆",
        dunyaSampiyonu: "WORLD CHAMPION",
        belirsiz: "TBD",
        henuzYok: "None Yet",
        gununMansetSkoru: "Headline Score:",
        tabloTakim: "Team",
        tabloO: "P", tabloG: "W", tabloB: "D", tabloM: "L",
        tabloAG: "GF", tabloYG: "GA", tabloAV: "GD", tabloP: "Pts",
        formda: "In Form", stabil: "Stable", formsuz: "Out of Form",
        enIyiUcuncuEtiket: "Best 3rd Place Standings",
        sira: "Pos",
        turSon32: "Round of 32",
        turSon16: "Round of 16",
        turCeyrek: "Quarter F.",
        turYari: "Semi F.",
        turUcunculuk: "3rd Place",
        turFinal: "Final",
        macGunuTamamla: "Complete Matchday",
        tumTuruOyna: "Simulate Entire Round",
        son32Gec: "Advance to Round of 32 🏆",
        sonrakiTuraGec: "Advance to Next Round ➡️",
        raporGoster: "📊 Tournament Report",
        macOynaButon: "▶️ Play",
        macRaporuBaslik: "Match Report",
        toplaOynama: "Possession",
        beklenenGol: "Expected Goals (xG)",
        toplamSut: "Total Shots",
        faul: "Fouls",
        sariKartlar: "Yellow Cards",
        kirmiziKartlar: "Red Cards",
        istatistikBaslik: "Tournament Statistics",
        keskinNisanci: "🎯 Sharpshooter",
        golOrani: "Conversion Rate",
        enKotuDefans: "🧱 Worst Defense",
        ygMac: "GA / Match",
        enBüyükSurpriz: "🔥 Biggest Surprise",
        hayalKirikligi: "😱 Disappointment",
        enKasapTakim: "⚔️ Most Aggressive",
        faulMac: "Fouls/Match",
        linkGizlilikMetni: "Privacy Policy",
        linkIletisimMetni: "Contact",
        iletisimFormuBaslik: "Contact Us",
        formAdiniz: "Your Name:",
        formEposta: "Your Email Address:",
        formMesajiniz: "Your Message:",
        formGonder: "Send Message 🚀",
        formGonderiliyor: "Sending...",
        formBasari: "Your message has been sent successfully!",
        hataEposta: "Please enter a valid email address.",
        hataGenel: "An error occurred while sending the message.",
        hataInternet: "Please check your internet connection.",
        kapat: "Close",
        silOnay: "Delete 🗑️",
        silVazgec: "Cancel",
        silBaslik: "Delete Career",
        silMetin: "All simulation data in the selected slot will be permanently deleted. Are you sure?",
        turUyarisi: "stage. Please complete this round first and use the 'Advance to Next Round' button!",
        gizlilikP1: "This World Cup 2026 Simulator uses <strong>local browser storage (LocalStorage)</strong> entirely to enhance user experience and keep your tournament records.",
        gizlilikP2: "No personal data, IP address, or simulation progress is transferred to remote servers, recorded, or shared with third parties. Your game is safe only on your own device.",
        
        modHizliSimule: "Quick Sim",
        modHizliSimuleAlt: "Just pick your team and simulate matches. Ideal for those who don't want to deal with tactical details.",
        modOzelGruplar: "Custom Groups",
        modOzelGruplarAlt: "Place teams in all 12 groups yourself or let the AI shuffle them! Create new scenarios without breaking the fixture structure.",
        modTaktiksel: "Tactical Mode",
        modTaktikselAlt: "Determine the starting XI, select formations, and adjust the game plan. Full control and deep managerial experience.",
        modSecimBaslik: "Select Game Mode",
        modSecimAlt: "How do you want to play the tournament?",
        cgBaslik: "Create Your Own Groups",
        cgAltMetin: "Drag and drop teams or click on the pool to send them to the next empty group.",
        cgBtnKaristir: "🎲 AI Shuffle",
        cgBtnSifirla: "🔄 Reset",
        cgBtnOnayla: "✅ Confirm & Continue",
        cgHavuzBaslik: "Team Pool",
        taktikYonetimiBtn: "Team Management 🧠",
        taktikTahtasi: "Tactics Board",
        oyunPlani: "Game Plan",
        ilk11Yedekler: "Starting XI & Subs"
    },

    de: {
        ziyaretciMetni: "Gesamte Besuche:",
        anaSayfaDon: "🏠 Startseite",
        anaBaslik: "WELTMEISTERSCHAFT 2026<br><span style='color:#fff;'>SIMULATOR</span>",
        altBaslik: "Verwalte dein Turnier, schreibe Geschichte neu.",
        slotKariyer: "Karriere",
        yeniKariyerAç: "Neue Karriere ➕",
        devamEt: "Fortsetzen 🎮",
        kariyeriSil: "Karriere löschen 🗑️",
        bosSlot: "Keine gespeicherte Karriere gefunden.",
        durumGrup: "Spieltag",
        durumSon32: "Runde der letzten 32",
        durumSon16: "Achtelfinale",
        durumCeyrek: "Viertelfinale",
        durumYari: "Halbfinale",
        durumSampiyon: "🏆 Meister gekrönt!",
        ilerleme: "Fortschritt",
        takimSecBaslik: "WÄHLE DEIN TEAM",
        takimSecAlt: "Mit welchem Land möchtest du den Weltmeistertitel holen?",
        secilenUlke: "Ausgewähltes Land:",
        grupMetni: "Gruppe",
        kariyerBaslat: "Karriere starten 🚀",
        iptalEt: "Abbrechen",
        hucum: "Angriff",
        ortaSaha: "Mittelfeld",
        savunma: "Abwehr",
        aktifKariyer: "Aktive Karriere: Slot",
        menajersiz: "Kein Manager",
        grupGoster: "Gruppenphase anzeigen 🔽",
        grupGizle: "Gruppenphase ausblenden 🔼",
        enIyiUcunculer: "Beste Gruppendritte",
        turnuvaDurumu: "Turnierstatus",
        grupAsamasiBitti: "Gruppenphase beendet!",
        elemeAgaci: "Weltmeisterschaft K.o.-Runde",
        buyukFinal: "GROSSES FINALE 🏆",
        dunyaSampiyonu: "WELTMEISTER",
        belirsiz: "Unbekannt",
        henuzYok: "Noch keine",
        gununMansetSkoru: "Schlagzeilen-Ergebnis:",
        tabloTakim: "Team",
        tabloO: "Sp", tabloG: "S", tabloB: "U", tabloM: "N",
        tabloAG: "T", tabloYG: "GT", tabloAV: "TD", tabloP: "Pkt",
        formda: "In Form", stabil: "Stabil", formsuz: "Formschwach",
        enIyiUcuncuEtiket: "Tabelle der Gruppendritten",
        sira: "Pl",
        turSon32: "Letzte 32",
        turSon16: "Achtelfinale",
        turCeyrek: "Viertel F.",
        turYari: "Halb F.",
        turUcunculuk: "Spiel um Platz 3",
        turFinal: "Finale",
        macGunuTamamla: "Spieltag abschließen",
        tumTuruOyna: "Gesamte Runde simulieren",
        son32Gec: "Weiter zur letzten 32 🏆",
        sonrakiTuraGec: "Zur nächsten Runde ➡️",
        raporGoster: "📊 Turnierbericht",
        macOynaButon: "▶️ Spielen",
        macRaporuBaslik: "Spielbericht",
        toplaOynama: "Ballbesitz",
        beklenenGol: "Erwartete Tore (xG)",
        toplamSut: "Schüsse Gesamt",
        faul: "Fouls",
        sariKartlar: "Gelbe Karten",
        kirmiziKartlar: "Rote Karten",
        istatistikBaslik: "Turnierstatistiken",
        keskinNisanci: "🎯 Scharfschütze",
        golOrani: "Torquote",
        enKotuDefans: "🧱 Schlechteste Abwehr",
        ygMac: "GT / Spiel",
        enBüyükSurpriz: "🔥 Größte Überraschung",
        hayalKirikligi: "😱 Enttäuschung",
        enKasapTakim: "⚔️ Aggressivstes Team",
        faulMac: "Fouls/Spiel",
        linkGizlilikMetni: "Datenschutzrichtlinie",
        linkIletisimMetni: "Kontakt",
        iletisimFormuBaslik: "Kontaktieren Sie uns",
        formAdiniz: "Ihr Name:",
        formEposta: "Ihre E-Mail-Adresse:",
        formMesajiniz: "Ihre Nachricht:",
        formGonder: "Nachricht senden 🚀",
        formGonderiliyor: "Wird gesendet...",
        formBasari: "Ihre Nachricht wurde erfolgreich gesendet!",
        hataEposta: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
        hataGenel: "Beim Senden der Nachricht ist ein Fehler aufgetreten.",
        hataInternet: "Bitte überprüfen Sie Ihre Internetverbindung.",
        kapat: "Schließen",
        silOnay: "Löschen 🗑️",
        silVazgec: "Abbrechen",
        silBaslik: "Karriere löschen",
        silMetin: "Alle Simulationsdaten in diesem Slot werden dauerhaft gelöscht. Bist du sicher?",
        turUyarisi: "Phase. Bitte schließe diese Runde zuerst ab und benutze die 'Zur nächsten Runde' Taste!",
        gizlilikP1: "Dieser WM 2026 Simulator verwendet ausschließlich <strong>lokalen Browserspeicher (LocalStorage)</strong>, um die Benutzererfahrung zu verbessern und Ihre Turnieraufzeichnungen zu speichern.",
        gizlilikP2: "Es werden keine persönlichen Daten, IP-Adressen oder Simulationsfortschritte an Remote-Server übertragen, aufgezeichnet oder an Dritte weitergegeben. Ihr Spiel ist nur auf Ihrem eigenen Gerät sicher.",
        
        modHizliSimule: "Schnelle Simulation",
        modHizliSimuleAlt: "Wähle einfach dein Team und simuliere die Spiele. Ideal für alle, die sich nicht mit taktischen Details befassen wollen.",
        modOzelGruplar: "Eigene Gruppen",
        modOzelGruplarAlt: "Platziere die Teams selbst in alle 12 Gruppen oder lass die KI sie mischen! Erstelle neue Szenarien, ohne die Struktur zu verändern.",
        modTaktiksel: "Taktikmodus",
        modTaktikselAlt: "Bestimme die Startelf, wähle Formationen und passe den Spielplan an. Volle Kontrolle und tiefes Manager-Erlebnis.",
        modSecimBaslik: "Spielmodus wählen",
        modSecimAlt: "Wie möchtest du das Turnier spielen?",
        cgBaslik: "Eigene Gruppen erstellen",
        cgAltMetin: "Ziehe Teams in die Gruppen oder klicke auf den Pool, um sie in die nächste freie Gruppe zu schicken.",
        cgBtnKaristir: "🎲 KI Mischen",
        cgBtnSifirla: "🔄 Zurücksetzen",
        cgBtnOnayla: "✅ Bestätigen",
        cgHavuzBaslik: "Team-Pool",
        taktikYonetimiBtn: "Team-Management 🧠",
        taktikTahtasi: "Taktiktafel",
        oyunPlani: "Spielplan",
        ilk11Yedekler: "Startelf & Ersatz"
    }
};